### PR TITLE
Meta tags moved to all pages for SEO

### PR DESCRIPTION
**Pull request by mumerfarooq000**
ticket link 
https://edlyio.atlassian.net/browse/EDE-830

description: for some public courses the syllabus and inner pages were accessible without login so SERP was not able to pick description as it was only on about page, moved the tags on all the pages so that public courses can have better SEO

### CODE REVIEW

**Review by HamzaIbnFarooq — CHANGES_REQUESTED** [review]
I don't think this will work... because main.html is being used on every page even there isn't any course selected. I believe we need to rethink the scenario.

**Comment by mumerfarooq000** [comment]
@HamzaIbnFarooq, yes, I will put the conditional statement.

**Comment by mumerfarooq000** [comment]
@HamzaIbnFarooq fixed and checked. thanks 👍

**Review by HamzaIbnFarooq — APPROVED** [review]

**Comment by mumerfarooq000** [comment]
Tested on staging, working fine, going to merge

**Pull request merged**
